name: Deploy EASI API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run API with HF Token
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Starting API server..."
        # Run your deployment command here
        # For example, if deploying to a service:
        # python deploy.py
        
        # Or just test that it starts:
        timeout 30 uvicorn api:app --host 0.0.0.0 --port 8000 || true
    
    # Add your deployment steps here
    # Examples:
    # - Deploy to AWS, GCP, Azure, Heroku, etc.
    # - Build and push Docker image
    # - Deploy to Kubernetes