services:
  - type: web
    name: easi-prediction-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0